services:
  base:
    build:
      context: .
      args:
        BASE_IMAGE: ${DEFAULT_DOCKER_REPO:+${DEFAULT_DOCKER_REPO}/}maven:3-amazoncorretto-17-al2023
    volumes:
      - .:/work
      - ${HOME}/.m2:/root/.m2
    working_dir: /work

  build:
    extends: base
    command:
      - mvn
      - -B
      - -ntp
      - -f
      - sonar-ps-plugin/pom.xml
      - clean
      - package

  test:
    extends: base
    command:
      - mvn
      - -B
      - -ntp
      - -f
      - sonar-ps-plugin/pom.xml
      - clean
      - test
